### PR TITLE
#162967778 user sign up form

### PR DESCRIPTION
**Pull request by TgeeT**
### *What does this PR do?*

Create user sign up form

 ### *Description of Task to be completed?*

Create HTML structure of the sign up and style it with CSS  
clicking the sign up button in the landing page redirects the user to the sign up form

### *How should this be manually tested?*

Clone this repo  
$git clone https://github.com/tgeet/Questioner.git  
$ cd Questioner  
Open index.html file using a browser

### *Any background context you want to provide?*

This is just a mere user interface

### *What are the relevant pivotal tracker stories?*

https://www.pivotaltracker.com/n/projects/2235327 [#162967778]

### screenshot
image

### CODE REVIEW

**Comment by Ogollah** [comment]
this is awsome.

**Comment by Mfalm3** [comment]
Awesome UI man!

**Comment by TgeeT** [comment]
### Add user sign up functionality to gh-pages

**Comment by TgeeT** [comment]
Thanks

**Pull request merged**
